[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lbfgsnew"
version = "0.1.0"
dependencies = []

dependencies = [
    "functools",
    "torch>=2.6.0",
]
